library(tidyverse)
library(dbplyr)
mechacar_db<-read.csv('MechaCar_mpg.csv',check.names = F, stringsAsFactors = F)
summary(lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,mechacar_db))
suspension_db<-read.csv('Suspension_Coil.csv',check.names = F, stringsAsFactors = F)
total_summary<-summarize(suspension_db,Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups='keep')
lot_summary<-suspension_db%>%group_by(Manufacturing_Lot)%>%summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI), .groups = 'keep')
t.test(suspension_db$PSI,mu=1500)
t.test(subset(suspension_db, Manufacturing_Lot=="Lot1")$PSI,mu=1500)
t.test(subset(suspension_db, Manufacturing_Lot=="Lot2")$PSI,mu=1500)
t.test(subset(suspension_db, Manufacturing_Lot=="Lot3")$PSI,mu=1500)
